In [1]:
### 기계공학과 4학년
### 20154523 강남규

## 배열 생성 예

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1)
print(arr1[3])
print(arr1[3:6])
print(arr1.shape)
print(arr1.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
4
[4 5 6]
(10,)
int32


In [5]:
arr2 = np.array([[1.0, 2.0, 3.0], [4.4, 5.5, 6.6]])
print(arr2)
print(arr2[1])
print(arr2[1,2])
print(arr2[1][2])
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
print(arr2.size)

[[1.  2.  3. ]
 [4.4 5.5 6.6]]
[4.4 5.5 6.6]
6.6
6.6
(2, 3)
float64
2
6


In [6]:
arr3 = np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 20, 21, 22]]])
print(arr3)
print(arr3[0])
print(arr3[1,2])
print(arr3[1,2,0])
print(arr3[1][2][0])
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)
print(arr3.size)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[19 20 21 22]
19
19
(2, 3, 4)
int32
3
24
