In [1]:
### 기계공학과 4학년
### 20154523 강남규

## 배열 연산 - 산술/비교 연산

In [2]:
import numpy as np

def pprint(arr, s):
    print("shape: {}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print(s)
    print(arr)

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pprint(a, "a's data =>")

b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
pprint(b, "b's data =>")

shape: (3, 3), dimension:2, dtype:int32
a's data =>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3), dimension:2, dtype:int32
b's data =>
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
c = a + b
pprint(c, "c = a + b =>")

shape: (3, 3), dimension:2, dtype:int32
c = a + b =>
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
d = a * b
pprint(d, "d = a * b =>")

shape: (3, 3), dimension:2, dtype:int32
d = a * b =>
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [6]:
e = a != b
pprint(e, "e = a != b =>")

shape: (3, 3), dimension:2, dtype:bool
e = a != b =>
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [7]:
f = a >= b
pprint(f, "f = a >= b =>")

shape: (3, 3), dimension:2, dtype:bool
f = a >= b =>
[[False False False]
 [False  True  True]
 [ True  True  True]]


## 배열 연산 - 수학 함수

In [9]:
h = np.sqrt(a)
pprint(h, "h = np.sqrt(a) =>")

shape: (3, 3), dimension:2, dtype:float64
h = np.sqrt(a) =>
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [10]:
g = np.cos(a)
pprint(g, "g = np.cos(a) =>")

shape: (3, 3), dimension:2, dtype:float64
g = np.cos(a) =>
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [11]:
m = np.dot(a, b)
pprint(m, "m = np.dot(a, b) =>")

shape: (3, 3), dimension:2, dtype:int32
m = np.dot(a, b) =>
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## 배열 연산 - 집계 함수 예1

In [13]:
# sum () 집계합수

s_none = a.sum()  # a.sum() == np.sum(a)
pprint(s_none, "s_none = a.sum() =>")

s_0 = a.sum(axis = 0) #np.sum(a, axis = 0)
pprint(s_0, "s_0 = a.sum(axis = 0) =>")

s_1 = a.sum(axis = 1) #np.sum(a, axis = 1)
pprint(s_1, "s_1 = a.sum(axis = 1) =>")

shape: (), dimension:0, dtype:int32
s_none = a.sum() =>
45
shape: (3,), dimension:1, dtype:int32
s_0 = a.sum(axis = 0) =>
[12 15 18]
shape: (3,), dimension:1, dtype:int32
s_1 = a.sum(axis = 1) =>
[ 6 15 24]


In [15]:
# max() 집계 함수

mx_none = a.max()
pprint(mx_none, "mx_none = a.max() =>")

mx_0 = a.max(axis = 0)
pprint(mx_0, "mx_0 = a.max(axis = 0) =>")

mx_1 = a.max(axis = 1)
pprint(mx_1, "mx_1 = a.max(axis = 1) =>")

shape: (), dimension:0, dtype:int32
mx_none = a.max() =>
9
shape: (3,), dimension:1, dtype:int32
mx_0 = a.max(axis = 0) =>
[7 8 9]
shape: (3,), dimension:1, dtype:int32
mx_1 = a.max(axis = 1) =>
[3 6 9]


In [19]:
# mean() 집계 함수

mn_none = a.mean()
pprint(mn_none, "mn_none = a.mean() =>")

mn_0 = a.mean(axis=0)
pprint(mn_0, "mn_0 = a.mean(axis=0) =>")

mn_1 = a.mean(axis=1)
pprint(mn_1, "mn_1 = a.mean(axis=1) =>")

shape: (), dimension:0, dtype:float64
mn_none = a.mean() =>
5.0
shape: (3,), dimension:1, dtype:float64
mn_0 = a.mean(axis=0) =>
[4. 5. 6.]
shape: (3,), dimension:1, dtype:float64
mn_1 = a.mean(axis=1) =>
[2. 5. 8.]


## 배열 연산 - 집계 함수 예 2

In [20]:
# 전체 성분의 최소값과 최대값이 위치한 인덱스를 반환한다.
# argmin, argmax 의 역할

agx = a.argmax()  # << np.argmax(a)
pprint(agx, "agx = a.argmax() =>")

agn = a.argmin()
pprint(agn, "agn = a.argmin() =>")

agx0 = a.argmax(axis = 0)
pprint(agx0, "agx0 = a.argmax(axis = 0) =>")

agx1 = a.argmax(axis = 1)
pprint(agx1, "agx1 = a.argmax(axis = 1) =>")

shape: (), dimension:0, dtype:int64
agx = a.argmax() =>
8
shape: (), dimension:0, dtype:int64
agn = a.argmin() =>
0
shape: (3,), dimension:1, dtype:int64
agx0 = a.argmax(axis = 0) =>
[2 2 2]
shape: (3,), dimension:1, dtype:int64
agx1 = a.argmax(axis = 1) =>
[2 2 2]


In [21]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산
# cumsum = 누적합 ,  cumprod = 누적곱

cs = a.cumsum()
pprint(cs, "cs = a.cumsum() =>")

cs1 = a.cumsum(axis = 1)
pprint(cs1, "cs1 = a.cumsum(axis = 1) =>")

shape: (9,), dimension:1, dtype:int32
cs = a.cumsum() =>
[ 1  3  6 10 15 21 28 36 45]
shape: (3, 3), dimension:2, dtype:int32
cs1 = a.cumsum(axis = 1) =>
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
