In [1]:
### 기계공학과 4학년
### 20154523 강남규

## BMI 검사

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np


def pprint(array, say='info'):
    print("shape: {}, dimension:{}, dtype:{}".format(array.shape, array.ndim, array.dtype))
    print(say)
    print(array)
    print("")
    
    
def cal_bmi(weights='40', heights='90'):           #bmi를 구하기 위한 함수, 몸무게와 키를 받아온다.
    #체중(kg)을 신장(m)의 제곱으로 나눈 값이 바로 체질량지수(BMI)입니다.
    bmi = np.array(weights) / np.array((heights/100)**2)    # 받아온 몸무게와 키를 bmi구하는 계산법으로 계산
                                    #kg을 m로 나눈 것이기 때문에 m로 계산해 주어야한다.
    pprint(bmi, "bmi")    #bmi를 출력
    return bmi    #bmi를 반환

def make_weight(sart_weight='40', end_weight='100', how_many='20'):    
    #how_many개의 sart_weight <= weight < end_weight의 범위를 가진 몸무게를 랜덤하게 생성해준다.
    #인수를 주지 않는다면 40~100 사이의 수 중 20개를 무작위로 선발한다.
    weights = np.random.randint(sart_weight, end_weight, size = how_many)
    pprint(weights, "weights")
    return weights
    
def make_height(sart_height='140', end_height='200', how_many='20'):
    #how_many개의 sart_height <= height < end_height의 범위를 가진 키를 랜덤하게 생성해준다.
    #인수를 주지 않는다면 140~200 사이의 수 중 20개를 무작위로 선발한다.
    heights = np.random.randint(sart_height, end_height, size = how_many)
    pprint(heights, "heights")
    return heights

#여기서 몸무게와 키는 리스트로 만들어도 되고, 이렇게 만드는 함수를 이용하여도 된다.

In [3]:
how_many = 20   #반복하는 횟수는 동일함
weights = make_weight(35, 110, how_many)
heights = make_height(140, 220, how_many)

bmi = cal_bmi(weights, heights)

shape: (20,), dimension:1, dtype:int32
weights
[ 51  75 105  43  70  72  90 105  68  71  39  75  56  41  81  70 107  67
 104  64]

shape: (20,), dimension:1, dtype:int32
heights
[171 187 169 156 169 177 199 160 142 146 164 178 144 196 161 166 199 161
 215 142]

shape: (20,), dimension:1, dtype:float64
bmi
[17.44126398 21.44756785 36.76341865 17.66929652 24.50894577 22.98190175
 22.72669882 41.015625   33.72346757 33.308313   14.50029744 23.67125363
 27.00617284 10.6726364  31.24879441 25.40281608 27.01951971 25.84776822
 22.49864792 31.73973418]



In [4]:
#보기 편하도록 행렬 변환
#how_many에 따라서 행렬을 자동 변환 시키려 하였지만
# how_many = n * m  꼴로 나타내려면 n과 m을 구해야하는데
# 이것을 구현하는데 몇몇 문제들이 많이 생겨 일단은 보류하였음.

weights_l = weights.reshape((4,5))
pprint(weights_l, "4X5 weights")

heights_l = heights.reshape((4,5))
pprint(heights_l, "4X5 weights")

bmi_l = bmi.reshape((4,5))
pprint(bmi_l, "4X5 weights")

shape: (4, 5), dimension:2, dtype:int32
4X5 weights
[[ 51  75 105  43  70]
 [ 72  90 105  68  71]
 [ 39  75  56  41  81]
 [ 70 107  67 104  64]]

shape: (4, 5), dimension:2, dtype:int32
4X5 weights
[[171 187 169 156 169]
 [177 199 160 142 146]
 [164 178 144 196 161]
 [166 199 161 215 142]]

shape: (4, 5), dimension:2, dtype:float64
4X5 weights
[[17.44126398 21.44756785 36.76341865 17.66929652 24.50894577]
 [22.98190175 22.72669882 41.015625   33.72346757 33.308313  ]
 [14.50029744 23.67125363 27.00617284 10.6726364  31.24879441]
 [25.40281608 27.01951971 25.84776822 22.49864792 31.73973418]]



In [5]:
# BMI <= 18.5 = 저체중
# 18.5 < BMI, BMI <= 23 = 정상
# 23 < BMI, BMI <= 25 = 과체중
# 25 < BMI, BMI <= 30 = 비만
# 30 < BMI, BMI <= 35 = 고도비만
# 35 < BMI = 초고도비만

low_bmi = bmi_l[bmi_l <= 18.5]
pprint(low_bmi, "Figure")
Low = len(low_bmi)
print(f"저체중은 {Low}명 입니다.")
cond = bmi_l <= 18.5
pprint(cond, "Low")

nom1_bmi = bmi_l[18.5 < bmi_l]
nom_bmi = nom1_bmi[nom1_bmi <= 23]
pprint(nom_bmi, "Figure")
nom = len(nom_bmi)
print(f"정상체중은 {nom}명 입니다.")
cond1 = bmi_l > 18.5
cond2 = bmi_l <= 23
cond = cond1 == cond2
pprint(cond, "nom")

over1_bmi = bmi_l[23 < bmi_l]
over_bmi = over1_bmi[over1_bmi <= 25]
pprint(over_bmi, "Figure")
overweight = len(over_bmi)
print(f"과체중은 {overweight}명 입니다.")
cond1 = bmi_l > 23
cond2 = bmi_l <= 25
cond = cond1 == cond2
pprint(cond, "overweight")

obe1_bmi = bmi_l[25 < bmi_l]
obe_bmi = obe1_bmi[obe1_bmi <= 30]
pprint(obe_bmi, "Figure")
obesity = len(obe_bmi)
print(f"비만은 {obesity}명 입니다.")
cond1 = bmi_l > 25
cond2 = bmi_l <= 30
cond = cond1 == cond2
pprint(cond, "obesity")

h_obe1_bmi = bmi_l[30 < bmi_l]
h_obe_bmi = h_obe1_bmi[h_obe1_bmi <= 35]
pprint(h_obe_bmi, "Figure")
h_obesity = len(h_obe_bmi)
print(f"고도체중은 {h_obesity}명 입니다.")
cond1 = bmi_l > 30
cond2 = bmi_l <= 35
cond = cond1 == cond2
pprint(cond, "h_obesity")

s_o_bmi = bmi_l[bmi_l > 35]
pprint(s_o_bmi, "Figure")
s_obesity = len(s_o_bmi)
print(f"초고도비만은 {s_obesity}명 입니다.")
cond = bmi_l > 35
pprint(cond, "s_obesity")

shape: (4,), dimension:1, dtype:float64
Figure
[17.44126398 17.66929652 14.50029744 10.6726364 ]

저체중은 4명 입니다.
shape: (4, 5), dimension:2, dtype:bool
Low
[[ True False False  True False]
 [False False False False False]
 [ True False False  True False]
 [False False False False False]]

shape: (4,), dimension:1, dtype:float64
Figure
[21.44756785 22.98190175 22.72669882 22.49864792]

정상체중은 4명 입니다.
shape: (4, 5), dimension:2, dtype:bool
nom
[[False  True False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False  True False]]

shape: (2,), dimension:1, dtype:float64
Figure
[24.50894577 23.67125363]

과체중은 2명 입니다.
shape: (4, 5), dimension:2, dtype:bool
overweight
[[False False False False  True]
 [False False False False False]
 [False  True False False False]
 [False False False False False]]

shape: (4,), dimension:1, dtype:float64
Figure
[27.00617284 25.40281608 27.01951971 25.84776822]

비만은 4명 입니다.
shape: (4, 5), dimension:2, dtype:bool
obe